-- AlterTable
ALTER TABLE "Procedure" ADD COLUMN "phase" INTEGER,
ADD COLUMN "tooth" TEXT,
ADD COLUMN "price" DOUBLE PRECISION,
ADD COLUMN "discount" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN "quantity" INTEGER DEFAULT 1;

